### ISSUE TITLE
"Norman Megill's initial plan to prove that the rational numbers are uncountable"

### ISSUE THREAD

**Issue by SKolodynski** [metamath/metamath-website-seed#23]
This is at https://us.metamath.org/mpeuni/mmcomplex.html#uncountable, I guess it was meant to be "real" instead "rational".

**Comment by BismaBRJ** [comment]
Outsider here from almost a year later. Opening that link, I see now that it does say "Norman Megill's initial plan to prove that the reals are uncountable" rather than the rational numbers. This issue should be closed by now, by whoever who can close it
